from __future__ import annotations

import hashlib
import re

from app.core.cache import TTLCache
from app.schemas import Skill

SKILL_CATALOG: dict[str, str] = {
    # Languages
    "python": "backend",
    "typescript": "frontend",
    "javascript": "frontend",
    "java": "backend",
    "c#": "backend",
    "c++": "backend",
    "golang": "backend",
    "rust": "backend",
    "ruby": "backend",
    "php": "backend",
    "swift": "mobile",
    "kotlin": "mobile",
    "scala": "backend",
    "r programming": "data",
    "matlab": "data",
    "perl": "backend",
    "dart": "mobile",
    "elixir": "backend",
    "haskell": "backend",
    "objective-c": "mobile",
    "sql": "database",
    "bash": "devops",
    "shell scripting": "devops",
    "powershell": "devops",
    "html": "frontend",
    "css": "frontend",
    "html5": "frontend",
    "css3": "frontend",
    # Frontend frameworks/tooling
    "react": "frontend",
    "next.js": "frontend",
    "nextjs": "frontend",
    "vue.js": "frontend",
    "vue": "frontend",
    "angular": "frontend",
    "svelte": "frontend",
    "redux": "frontend",
    "tailwind css": "frontend",
    "tailwindcss": "frontend",
    "bootstrap": "frontend",
    "sass": "frontend",
    "webpack": "frontend",
    "vite": "frontend",
    "jquery": "frontend",
    # Backend frameworks
    "fastapi": "backend",
    "django": "backend",
    "flask": "backend",
    "express.js": "backend",
    "express": "backend",
    "nestjs": "backend",
    "spring boot": "backend",
    "spring": "backend",
    "ruby on rails": "backend",
    "rails": "backend",
    "laravel": "backend",
    "asp.net": "backend",
    "node.js": "backend",
    "graphql": "backend",
    "grpc": "backend",
    "rest api": "backend",
    "microservices": "backend",
    "api": "backend",
    # Mobile
    "react native": "mobile",
    "flutter": "mobile",
    "swiftui": "mobile",
    "android": "mobile",
    "ios": "mobile",
    "xamarin": "mobile",
    # Databases
    "postgres": "database",
    "postgresql": "database",
    "mysql": "database",
    "mongodb": "database",
    "redis": "database",
    "cassandra": "database",
    "dynamodb": "database",
    "oracle": "database",
    "sql server": "database",
    "mariadb": "database",
    "elasticsearch": "database",
    "neo4j": "database",
    "supabase": "database",
    "firebase": "database",
    "snowflake": "data",
    "bigquery": "data",
    "redshift": "data",
    # AI / data
    "langgraph": "ai",
    "langchain": "ai",
    "llm": "ai",
    "rag": "ai",
    "machine learning": "ai",
    "deep learning": "ai",
    "artificial intelligence": "ai",
    "generative ai": "ai",
    "prompt engineering": "ai",
    "tensorflow": "ai",
    "pytorch": "ai",
    "keras": "ai",
    "scikit-learn": "ai",
    "nlp": "ai",
    "computer vision": "ai",
    "hugging face": "ai",
    "openai": "ai",
    "gpt": "ai",
    "transformers": "ai",
    "vector database": "ai",
    "pinecone": "ai",
    "weaviate": "ai",
    "chromadb": "ai",
    "data science": "data",
    "data engineering": "data",
    "data analysis": "analytics",
    "etl": "data",
    "spark": "data",
    "apache spark": "data",
    "hadoop": "data",
    "airflow": "data",
    "kafka": "data",
    "dbt": "data",
    "mlops": "ai",
    "pandas": "data",
    "numpy": "data",
    # DevOps / cloud
    "docker": "devops",
    "kubernetes": "devops",
    "terraform": "devops",
    "ansible": "devops",
    "jenkins": "devops",
    "ci/cd": "devops",
    "github actions": "devops",
    "gitlab ci": "devops",
    "cloudformation": "cloud",
    "aws": "cloud",
    "gcp": "cloud",
    "azure": "cloud",
    "vercel": "cloud",
    "render": "cloud",
    "heroku": "cloud",
    "nginx": "devops",
    "linux": "devops",
    "git": "devops",
    "github": "devops",
    "gitlab": "devops",
    "prometheus": "devops",
    "grafana": "devops",
    "datadog": "devops",
    "cloudwatch": "devops",
    # Testing / QA
    "pytest": "testing",
    "playwright": "testing",
    "jest": "testing",
    "mocha": "testing",
    "cypress": "testing",
    "selenium": "testing",
    "junit": "testing",
    "unit testing": "testing",
    "integration testing": "testing",
    "tdd": "testing",
    "qa automation": "testing",
    "load testing": "testing",
    "test automation": "testing",
    # Security
    "security": "security",
    "oauth": "security",
    "jwt": "security",
    "penetration testing": "security",
    "security auditing": "security",
    "encryption": "security",
    "owasp": "security",
    "siem": "security",
    "iam": "security",
    "vulnerability assessment": "security",
    "incident response": "security",
    "compliance": "security",
    "gdpr": "security",
    "hipaa": "security",
    "soc 2": "security",
    "pci dss": "security",
    "zero trust": "security",
    # Project / product management
    "project management": "operations",
    "stakeholder management": "operations",
    "agile": "operations",
    "scrum": "operations",
    "kanban": "operations",
    "waterfall": "operations",
    "jira": "operations",
    "confluence": "operations",
    "product management": "product",
    "program management": "operations",
    "prince2": "operations",
    "pmp": "operations",
    # Design / product
    "figma": "design",
    "sketch": "design",
    "adobe xd": "design",
    "ui/ux design": "design",
    "graphic design": "design",
    "photoshop": "design",
    "illustrator": "design",
    "indesign": "design",
    "wireframing": "design",
    "prototyping": "design",
    "user research": "design",
    "product design": "design",
    "web design": "design",
    # Analytics / BI
    "tableau": "analytics",
    "power bi": "analytics",
    "looker": "analytics",
    "google analytics": "analytics",
    "data visualization": "analytics",
    "a/b testing": "analytics",
    "business intelligence": "analytics",
    "sql reporting": "analytics",
    "excel": "analytics",
    # Sales / marketing
    "sales": "commercial",
    "marketing": "commercial",
    "seo": "commercial",
    "sem": "commercial",
    "content strategy": "commercial",
    "content marketing": "commercial",
    "email marketing": "commercial",
    "social media marketing": "commercial",
    "digital marketing": "commercial",
    "salesforce": "commercial",
    "hubspot": "commercial",
    "crm": "commercial",
    "lead generation": "commercial",
    "copywriting": "commercial",
    "brand strategy": "commercial",
    "google ads": "commercial",
    "growth marketing": "commercial",
    "community management": "commercial",
    # Finance / accounting
    "accounting": "finance",
    "financial analysis": "finance",
    "financial modeling": "finance",
    "bookkeeping": "finance",
    "quickbooks": "finance",
    "sap": "finance",
    "budgeting": "finance",
    "forecasting": "finance",
    "audit": "finance",
    "tax preparation": "finance",
    "gaap": "finance",
    "investment analysis": "finance",
    "risk management": "finance",
    "treasury": "finance",
    "erp": "finance",
    "kpi": "analytics",
    "roi": "finance",
    "ppc": "commercial",
    "b2b": "commercial",
    "b2c": "commercial",
    # Operations / supply chain
    "operations": "operations",
    "supply chain management": "operations",
    "logistics": "operations",
    "inventory management": "operations",
    "procurement": "operations",
    "six sigma": "operations",
    "lean manufacturing": "operations",
    "vendor management": "operations",
    "quality assurance": "operations",
    "quality control": "operations",
    # HR
    "recruiting": "hr",
    "talent acquisition": "hr",
    "onboarding": "hr",
    "performance management": "hr",
    "hris": "hr",
    "payroll": "hr",
    "employee relations": "hr",
    "compensation and benefits": "hr",
    # Legal
    "litigation": "legal",
    "legal research": "legal",
    "intellectual property": "legal",
    "legal drafting": "legal",
    "due diligence": "legal",
    # Healthcare
    "clinical research": "healthcare",
    "patient care": "healthcare",
    "ehr": "healthcare",
    "nursing": "healthcare",
    "medical coding": "healthcare",
    "clinical trials": "healthcare",
    "pharmacovigilance": "healthcare",
    "healthcare administration": "healthcare",
    # Education
    "curriculum development": "education",
    "instructional design": "education",
    "tutoring": "education",
    "classroom management": "education",
    "e-learning": "education",
    "lms": "education",
    # Customer support / service
    "customer service": "service",
    "customer success": "service",
    "technical support": "service",
    "help desk": "service",
    "zendesk": "service",
    # Soft skills
    "communication": "general",
    "leadership": "general",
    "teamwork": "general",
    "problem solving": "general",
    "critical thinking": "general",
    "time management": "general",
    "adaptability": "general",
    "negotiation": "general",
    "public speaking": "general",
    "mentoring": "general",
    "collaboration": "general",
    "conflict resolution": "general",
    "decision making": "general",
}

_SKILL_CACHE: TTLCache[list[Skill]] = TTLCache(max_size=256, ttl_seconds=30 * 60)


def extract_skills(text: str) -> list[Skill]:
    cache_key = hashlib.sha256(text.encode("utf-8")).hexdigest()
    cached = _SKILL_CACHE.get(cache_key)
    if cached is not None:
        return [skill.model_copy() for skill in cached]

    normalized = text.lower()
    found: list[Skill] = []
    for skill, category in SKILL_CATALOG.items():
        pattern = rf"(?<![a-z0-9]){re.escape(skill)}(?![a-z0-9])"
        if re.search(pattern, normalized):
            found.append(Skill(name=_display_name(skill), category=category, confidence=0.82))

    if not found:
        found.append(Skill(name="Communication", category="general", confidence=0.45))

    skills = dedupe_skills(found)
    _SKILL_CACHE.set(cache_key, [skill.model_copy() for skill in skills])
    return skills


def dedupe_skills(skills: list[Skill]) -> list[Skill]:
    seen: set[str] = set()
    result: list[Skill] = []
    for skill in skills:
        key = skill.name.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(skill)
    return result


def _display_name(skill: str) -> str:
    names = {
        "nextjs": "Next.js",
        "next.js": "Next.js",
        "typescript": "TypeScript",
        "javascript": "JavaScript",
        "fastapi": "FastAPI",
        "langgraph": "LangGraph",
        "langchain": "LangChain",
        "postgres": "Postgres",
        "postgresql": "PostgreSQL",
        "supabase": "Supabase",
        "playwright": "Playwright",
        "pytest": "Pytest",
        "llm": "LLM",
        "rag": "RAG",
        "api": "API",
        "sql": "SQL",
        "aws": "AWS",
        "gcp": "GCP",
        "seo": "SEO",
        "r programming": "R",
        "vue.js": "Vue.js",
        "express.js": "Express.js",
        "nestjs": "NestJS",
        "ruby on rails": "Ruby on Rails",
        "asp.net": "ASP.NET",
        "node.js": "Node.js",
        "graphql": "GraphQL",
        "grpc": "gRPC",
        "rest api": "REST API",
        "ci/cd": "CI/CD",
        "github actions": "GitHub Actions",
        "gitlab ci": "GitLab CI",
        "cloudformation": "CloudFormation",
        "github": "GitHub",
        "gitlab": "GitLab",
        "cloudwatch": "CloudWatch",
        "mysql": "MySQL",
        "mongodb": "MongoDB",
        "dynamodb": "DynamoDB",
        "sql server": "SQL Server",
        "mariadb": "MariaDB",
        "neo4j": "Neo4j",
        "bigquery": "BigQuery",
        "tensorflow": "TensorFlow",
        "pytorch": "PyTorch",
        "scikit-learn": "scikit-learn",
        "nlp": "NLP",
        "etl": "ETL",
        "mlops": "MLOps",
        "openai": "OpenAI",
        "gpt": "GPT",
        "chromadb": "ChromaDB",
        "iam": "IAM",
        "jwt": "JWT",
        "owasp": "OWASP",
        "siem": "SIEM",
        "gdpr": "GDPR",
        "hipaa": "HIPAA",
        "soc 2": "SOC 2",
        "pci dss": "PCI DSS",
        "prince2": "PRINCE2",
        "pmp": "PMP",
        "adobe xd": "Adobe XD",
        "ui/ux design": "UI/UX Design",
        "hubspot": "HubSpot",
        "quickbooks": "QuickBooks",
        "sap": "SAP",
        "gaap": "GAAP",
        "erp": "ERP",
        "kpi": "KPI",
        "roi": "ROI",
        "ppc": "PPC",
        "b2b": "B2B",
        "b2c": "B2C",
        "sem": "SEM",
        "hris": "HRIS",
        "ehr": "EHR",
        "lms": "LMS",
        "ios": "iOS",
        "swiftui": "SwiftUI",
        "power bi": "Power BI",
        "sql reporting": "SQL Reporting",
        "tdd": "TDD",
        "qa automation": "QA Automation",
    }
    return names.get(skill, skill.title())
